version: "3.8"

services:
  api:
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: "/static/"
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - db
      - rabbitmq
    volumes:
      # shared volume between worker and api for media
      - media-storage:/app/media
    command: python manage.py runserver 0.0.0.0:8000
    env_file: common.env

  db:
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - db-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=api

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672 # AMQP protocol port
        - 15672:15672 # HTTP management UI
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    restart: unless-stopped
    networks:
      - backend

  worker:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: "/static/"
    command: celery -A project --app=project.celeryconf:app worker --loglevel=info -B
    restart: unless-stopped
    networks:
      - backend
    env_file: common.env
    depends_on:
      - rabbitmq
      - mailhog
    volumes:
      # shared volume between worker and api for media
      - media-storage:/app/media

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui. Visit http://localhost:8025/ to check emails
    restart: unless-stopped
    networks:
      - backend

volumes:
  db-storage:
    driver: local
  media-storage:

networks:
  backend:
    driver: bridge
