# Generated by Django 3.2.12 on 2022-02-06 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_follow_uuid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
    ]
